aac対応してmp3に対応してアイコンクリックでoptionページを開くようにしました
masteralice3104/nico_downloader pull request #10
Opened 2024-11-04 08:06 UTC by SUKEsann2000

aacとmp3に対応したんですが、aacはFFmpegでコピーできたのですが、mp3はどうやらコピーできないらしいので時間がかかります。
アイコンクリックでoptionページを開くようにしたのは誰でもモードの変更が楽になるかと思ったからです。ﾊｲ

2024-11-04 08:11 UTC, SUKEsann2000 commented
5.0.0.13からコピーしてきたんでタグ関連のバグとか競合起きるかもしれないです。すません！
（現に今バージョンの競合起きてる...）

2024-11-08 09:36 UTC, SUKEsann2000 commented
ミスってclosedしちゃいました...

2024-11-09 08:40 UTC, SUKEsann2000 commented
微調整しました！
utils.jsでoption_setloadingを多用していた→downFile_settingに修正
optionページでoptions.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'innerText')というエラーが出るので回避

2024-11-09 16:57 UTC, masteralice3104 requested changes
**[MUST]**
- 機能の変更点別及びREADMEの変更、それぞれ別にプルリクを分けて下さい
- [ひとつのPullRequestにはひとつの目的](https://zenn.dev/nekoya/articles/adc9ec4b08e4f3#%E3%81%9D%E3%83%97%E3%83%87%E3%82%AB:~:text=%E3%81%8C%E9%87%8D%E8%A6%81%E3%81%A7%E3%81%99%E3%80%82-,%E3%81%B2%E3%81%A8%E3%81%A4%E3%81%AEPullRequest%E3%81%AB%E3%81%AF%E3%81%B2%E3%81%A8%E3%81%A4%E3%81%AE%E7%9B%AE%E7%9A%84,-PR%E3%81%AF%E3%81%B2%E3%81%A8%E3%81%A4)

**[NITS]**
- READMEやoptions.htmlなど表に出る部分はもう少し表現を変えるべきかと思います

**[IMO]**
- utils.jsのOption_setLoading()はoption.jsのOption_setLoading()との共通化のためあえて使用しています
-  [アイコンクリックで保存ボタンを表示する用法が存在する](https://golabo.net/yarikata_download_nicovideo/#:~:text=%E8%89%AF%E3%81%84%E4%BE%8B-,%E4%BB%BB%E6%84%8F%E3%81%AE%E3%82%BF%E3%82%A4%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%A7%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B%EF%BC%88%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%EF%BC%89,-%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%A2%E3%83%83%E3%83%97%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6%E4%BD%BF%E3%81%84)
- エラー表示内容がStringで済む場合はできるだけDebugPrintを使用する方針です

**[ほか]**
- OutputFileNameSetやFSOutputFileNameSetあたりの関数は変更中です
- そのあたり触るとコンフリクトする恐れがあります

2024-11-16 05:46 UTC, closed without merging

2024-11-16 06:20 UTC, SUKEsann2000 commented
ご指摘ありがとうございます！
少しぐちゃぐちゃになってしまったので一回Closeして出直してきます！